name: rescenescribe-camera-only
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pillow
  - plyfile
  - trimesh
  - opencv
  - matplotlib
  - pip
  - pip:
      - ultralytics>=8.3
